-- Fix Staff Database Structure and Data
-- This script converts staff_id from INT to VARCHAR and inserts proper credentials

-- Step 1: Drop existing constraints if they exist
SET FOREIGN_KEY_CHECKS=0;

-- Step 2: Backup and clear
DELETE FROM department_staff;

-- Step 3: Modify table structure
-- Change staff_id from INT to VARCHAR
ALTER TABLE department_staff DROP PRIMARY KEY;
ALTER TABLE department_staff MODIFY COLUMN staff_id VARCHAR(50) NOT NULL;
ALTER TABLE department_staff ADD PRIMARY KEY (staff_id);

-- Make email nullable
ALTER TABLE department_staff MODIFY COLUMN email VARCHAR(100) NULL;

-- Step 4: Add profile_completed column if not exists
-- ALTER TABLE department_staff ADD COLUMN profile_completed TINYINT(1) DEFAULT 0;

-- Step 5: Insert staff with department-based credentials
-- Passwordhashes for the passwords provided (will be generated by PHP)
-- This is a template - passwords need to be hashed
INSERT INTO department_staff (staff_id, dept_id, name, email, password, profile_completed, created_at) VALUES
('CSE-001', 1, 'CSE Coordinator', 'cse@college.edu', '$2y$10$placeholder_hash_1', 0, NOW()),
('ECE-002', 2, 'ECE Coordinator', 'ece@college.edu', '$2y$10$placeholder_hash_2', 0, NOW()),
('ME-003', 3, 'ME Coordinator', 'me@college.edu', '$2y$10$placeholder_hash_3', 0, NOW()),
('CE-004', 4, 'CE Coordinator', 'ce@college.edu', '$2y$10$placeholder_hash_4', 0, NOW()),
('IT-005', 5, 'IT Coordinator', 'it@college.edu', '$2y$10$placeholder_hash_5', 0, NOW()),
('VLSI-006', 6, 'VLSI Coordinator', 'vlsi@college.edu', '$2y$10$placeholder_hash_6', 0, NOW()),
('EEE-007', 7, 'EEE Coordinator', 'eee@college.edu', '$2y$10$placeholder_hash_7', 0, NOW()),
('AIML-008', 8, 'AIML Coordinator', 'aiml@college.edu', '$2y$10$placeholder_hash_8', 0, NOW()),
('AIDS-009', 9, 'AIDS Coordinator', 'aids@college.edu', '$2y$10$placeholder_hash_9', 0, NOW());

-- Step 6: Verify
SELECT 'Staff Database Updated' as Status;
SELECT staff_id, name, dept_id, email FROM department_staff ORDER BY staff_id;

SET FOREIGN_KEY_CHECKS=1;
